version: '3'

service:
  tomcat:
    build:
      context: .
      dockerfile: /apps/sample/Dockerfile
    ports:
      - "80:8080"
    volumes:
    - /logs/:/usr/local/tomcat/logs/
    - /data/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
