version: '3.7'

services:
  tomcat:
    build: .
    image: sangwondocker/temp
    container_name: tomcat-container
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./mydata:/usr/local/tomcat/webapps

volumes: 
  mydata:
